# Generated by Django 6.0.8 on 2026-08-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchparticipant',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('left', 'Left'), ('waiting', 'Waiting')], default='confirmed', max_length=20),
        ),
    ]
