# Generated by Django 6.0.7 on 2026-09-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_joinrequest_options_and_more'),
        ('matches', '0005_alter_matchparticipant_status'),
    ]

    operations = [
    ]
