# Generated by Django 6.0.7 on 2026-09-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_merge_20260901_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
