# Generated by Django 6.0.8 on 2026-09-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favoriteplayer'),
        ('users', '0003_report'),
    ]

    operations = [
    ]
